// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:184580940908:web:6bce3a100b17dbfd022449',
        messagingSenderId: '184580940908',
        projectId: 'gaslight-46368',
        authDomain: 'gaslight-46368.firebaseapp.com',
        storageBucket: 'gaslight-46368.firebasestorage.app',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
        appId: '1:184580940908:android:8e063ee8fd11c733022449',
        messagingSenderId: '184580940908',
        projectId: 'gaslight-46368',
        storageBucket: 'gaslight-46368.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:184580940908:ios:39742ab201759265022449',
        messagingSenderId: '184580940908',
        projectId: 'gaslight-46368',
        storageBucket: 'gaslight-46368.firebasestorage.app',
        iosBundleId: 'com.example.gaslight',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:184580940908:ios:39742ab201759265022449',
        messagingSenderId: '184580940908',
        projectId: 'gaslight-46368',
        storageBucket: 'gaslight-46368.firebasestorage.app',
        iosBundleId: 'com.example.gaslight',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:184580940908:web:61d3f0cfc6532bee022449',
        messagingSenderId: '184580940908',
        projectId: 'gaslight-46368',
        authDomain: 'gaslight-46368.firebaseapp.com',
        storageBucket: 'gaslight-46368.firebasestorage.app',
      );
}
